-- Source values are recorded, not treated as live Cardmarket feeds or retail inventory.
insert into public.commerce_sourcing_candidates
(sora_reference,name,set_code,language,format,sora_url,cardmarket_url,
 market_floor_cents,market_trend_cents,market_avg30_cents,market_avg7_cents,
 market_avg1_cents,market_listings_count,market_source,market_snapshot_date,market_notes,
 sora_b2b_quote_jpy,sora_b2b_eur_cents,sora_quote_source,fx_rate_date,decision,decision_reason)
values
('TK-0046','Pokémon Card 151','sv2a','JP','BOOSTER_BOX',
'https://sora-cardshop.com/product/TK-0046',
'https://www.cardmarket.com/es/Pokemon/Products/Booster-Boxes/Pokemon-Card-151-Booster-Box',
15000,22719,null,null,null,507,'WEB_INDEXED',null,
'Cardmarket indexado cerca de 6 días antes del 08/10. Foto 08/10 sin estadísticas legibles. Verificar precinto shrink original.',
null,null,null,null,'PENDING_QUOTE','Pedir precio B2B y condiciones de sellado en Sora.'),
('TK-0001','MEGA Dream ex','M2a','JP','BOOSTER_BOX',
'https://sora-cardshop.com/product/TK-0001',
'https://www.cardmarket.com/es/Pokemon/Products/Booster-Boxes/MEGA-Dream-ex-Booster-Box',
7000,8053,8273,8148,8296,1748,'USER_SCREENSHOT','2026-10-08',
'Fotografía Cardmarket 08/10; booster box individual, no CASE.',
null,null,null,null,'PENDING_QUOTE','Pendiente coste Sora B2B.'),
('TK-0030','Glory of Team Rocket','sv10','JP','BOOSTER_BOX',
'https://sora-cardshop.com/product/TK-0030',
'https://www.cardmarket.com/es/Pokemon/Products/Booster-Boxes/The-Glory-of-Team-Rocket-Booster-Box',
4450,7329,8146,8122,10021,973,'WEB_INDEXED',null,
'Fotografía sin cifras legibles; valores indexados semanas antes. Verificar precio actual, JP y shrink.',
null,null,null,null,'PENDING_QUOTE','Pendiente cotejar condiciones y coste Sora.'),
('TK-0003','Inferno X','M2','JP','BOOSTER_BOX',
'https://sora-cardshop.com/product/TK-0003',
'https://www.cardmarket.com/es/Pokemon/Products/Booster-Boxes/Inferno-X-Booster-Box',
8500,7380,7196,7544,6505,676,'USER_SCREENSHOT','2026-10-08',
'Fotografía Cardmarket 08/10. No confundir con Inferno X coreano ni CASE.',
null,null,null,null,'PENDING_QUOTE','Pendiente precio B2B y portes.'),
('TK-0164','30th CELEBRATION','M6a','JP','BOOSTER_BOX',
'https://sora-cardshop.com/product/TK-0164',
'https://www.cardmarket.com/es/Pokemon/Products/Booster-Boxes/30th-Celebration-JP-Booster-Box',
17000,15216,16173,16196,16286,657,'USER_SCREENSHOT','2026-10-08',
'La cotización comercial del proveedor se conserva solo en Supabase privado, no en código público.',
null,null,null,null,'REVIEW','Introducir la cotización privada y validar margen neto antes de decidir.'),
('TK-0176','Storm Emeralda','M6','JP','BOOSTER_BOX',
'https://sora-cardshop.com/product/TK-0176',
'https://www.cardmarket.com/es/Pokemon/Products/Booster-Boxes/Storm-Emeralda-Booster-Box',
7490,7212,7637,7371,7323,1313,'USER_SCREENSHOT','2026-10-08',
'Foto Cardmarket 08/10; nombre en Sora Storm Emeralda [M6].',
null,null,null,null,'PENDING_QUOTE','Pendiente precio B2B puesto en España.'),
('TK-0165','30th CELEBRATION Espeon ex / Umbreon ex Premium Deck Set','mF','JP','PREMIUM_DECK_SET',
'https://sora-cardshop.com/product/TK-0165',
'https://www.cardmarket.com/es/Pokemon/Products/Box-Sets/30th-Celebration-Espeon-ex-and-Umbreon-ex-Premium-Deck-Set',
15499,13301,16377,16431,16036,200,'USER_SCREENSHOT','2026-10-08',
'NO ES BOOSTER BOX: Premium Deck Set. Se registra como exclusión de calidad.',
null,null,null,null,'EXCLUDED','Descartado por formato. Soriko solo compara booster boxes selladas en esta selección.')
on conflict(sora_reference) do nothing;
